; ============================================================
; Generated by pic18-c-compiler (teaching-quality codegen).
; Target chip: PIC18F4520. Adjust LIST/include/CONFIG as needed.
; ============================================================
        LIST    P=18F4520
        #include <p18f4520.inc>

; --- Configuration bits ------------------------------------
; NOTE: tweak these to match your hardware. We default to a
;       safe internal-oscillator setup with WDT disabled.
        CONFIG  OSC = INTIO67
        CONFIG  WDT = OFF
        CONFIG  LVP = OFF
        CONFIG  MCLRE = OFF
        CONFIG  PBADEN = DIG

; --- Variables (access bank) -------------------------------
ACS_VARS UDATA_ACS
R0                      RES     1
R1                      RES     1
R2                      RES     1
R3                      RES     1
R4                      RES     1
R5                      RES     1
R6                      RES     1
R7                      RES     1
ARG0                    RES     1
ARG1                    RES     1
ARG2                    RES     1
ARG3                    RES     1
RETVAL                  RES     1
DELAY_OUTER             RES     1
DELAY_INNER             RES     1
EVAL_STACK              RES     16

; --- Reset vector ------------------------------------------
RESETV  CODE    0x0000
        GOTO    MAIN

; --- High-priority interrupt vector (placeholder) ----------
HIISR   CODE    0x0008
        RETFIE  FAST

; --- Low-priority interrupt vector (placeholder) -----------
LOISR   CODE    0x0018
        RETFIE  FAST

; --- Program code ------------------------------------------
PROG    CODE

; locals for main()
LOC_main  UDATA_ACS
F_main__LOC_i           RES     1
F_main__LOC_a           RES     1
PROG    CODE

; ===== function main() =====
MAIN:
        CLRF    F_main__LOC_i, A
        CLRF    F_main__LOC_a, A
        ; expression-statement
        ; out(1 /* LATB */, expr)
        MOVLW   0x00
        MOVWF   LATB, A   ; drive port
        ; while (...)
WHILE_0:
        MOVLW   0x01
        IORLW   0
        BZ      WEND_1
        ; expression-statement
        ; out(1 /* LATB */, expr)
        MOVLW   0x01
        MOVWF   LATB, A   ; drive port
        ; expression-statement
        ; delay(n)
        MOVLW   0xC8
        MOVWF   ARG0, A
        CALL    F_delay, 0
        ; expression-statement
        ; out(1 /* LATB */, expr)
        MOVLW   0x00
        MOVWF   LATB, A   ; drive port
        ; expression-statement
        ; delay(n)
        MOVLW   0xC8
        MOVWF   ARG0, A
        CALL    F_delay, 0
        BRA     WHILE_0
WEND_1:
        ; for (...)
        MOVLW   0x00
        MOVWF   F_main__LOC_a, A
FOR_2:
        MOVF    F_main__LOC_a, W, A
        MOVWF   EVAL_STACK+0, A   ; push (sp=0)
        MOVLW   0x0A
        CPFSGT  EVAL_STACK+0, A   ; skip next if < true
        BRA     CMP_F_4
        MOVLW   0x01
        BRA     CMP_E_5
CMP_F_4:
        MOVLW   0x00
CMP_E_5:
        IORLW   0
        BZ      FEND_3
        ; expression-statement
        ; out(1 /* LATB */, expr)
        MOVLW   0x01
        MOVWF   LATB, A   ; drive port
        ; expression-statement
        ; delay(n)
        MOVLW   0xC8
        MOVWF   ARG0, A
        CALL    F_delay, 0
        ; expression-statement
        ; out(1 /* LATB */, expr)
        MOVLW   0x00
        MOVWF   LATB, A   ; drive port
        ; expression-statement
        ; delay(n)
        MOVLW   0xC8
        MOVWF   ARG0, A
        CALL    F_delay, 0
        ; post-inc a
        MOVF    F_main__LOC_a, W, A      ; W = old a
        INCF    F_main__LOC_a, F, A      ; a++ (W keeps old value)
        BRA     FOR_2
FEND_3:
        MOVLW   0x00
        MOVWF   RETVAL, A
        RETURN
        RETURN
        ; max expr-stack depth used here: 1

; ===== runtime: delay(n) — nested decrement loop ======
F_delay:
        MOVF    ARG0, W, A
        MOVWF   DELAY_OUTER, A
        BZ      F_delay_done
F_delay_outer:
        MOVLW   0xFF
        MOVWF   DELAY_INNER, A
F_delay_inner:
        DECFSZ  DELAY_INNER, F, A
        BRA     F_delay_inner
        DECFSZ  DELAY_OUTER, F, A
        BRA     F_delay_outer
F_delay_done:
        RETURN

        END
